### ISSUE TITLE
DBFZ - Attempting to parse any script returns error

### ISSUE THREAD

**Issue by JoeyLoey** [super-continent/bbscript#18]
Version: 0.9.1
Attempting to parse any script from DBFZ yells out this error:
"←[1;31merror←[0m: Unknown instruction with ID/name `1598837826`"
The numbers change depending on the file. In this case, I was attempting to parse GKB's uasset and uexp's bbscript file.

**Comment by JoeyLoey** [comment]
Turns out this is fixed just by messing with the .ron for the game.

**Comment by LumiKattlin** [comment]
> 

how ?

**Comment by super-continent** [comment]
the config has been updated, should no longer have this issue.
