### ISSUE TITLE
Labeling the p4u2.ron?

### ISSUE THREAD

**Issue by jeffdiom** [super-continent/bbscript#19]
You don't mind if I do the labeling for the .ron for you for your next update?

**Comment by jeffdiom** [comment]
I got the list of the unknowns that I already discovered (Including the args too)

**Comment by super-continent** [comment]
if you add any labels to the config go ahead and create a PR for them, I'll suggest edits to keep naming conventions uniform and such

**Comment by jeffdiom** [comment]
Bet
