### ISSUE TITLE
Parsing DNF files

### ISSUE THREAD

**Issue by AshSuqs** [super-continent/bbscript#26]
Currently trying to parse the bbscript files and the current version says it supports DNF but every attempt just returns the error
"ERROR: Config contains multiple instances of an instruction named `addObjectSize`"
I am attempting this specifically with extracted "RED\Content\Chara\03A\Common\Data\BBS_03A"
Not sure if this is an issue with the patch that went through a couple months back or if it is a fault of my own somehow.

**Comment by AshSuqs** [comment]
Okay so it wasn't an issue of the game getting an update in that time or my own, the "dnf.ron" file is just faulty. The file has a duplicate command at 388 that is "addObjectSize" when it should be "objectSizePercent".
An easy fix but I feel it should have at least been tested before doing a release.

**Comment by super-continent** [comment]
these were tested unfortunately its easy for issues like this to slip through the cracks, i don't remember who original authored the dnf.ron file but it was probably before this issue was automatically detected and reported by bbscript. will try to work on fixing the config, not sure why there are 2 duplicate names here

**Comment by super-continent** [comment]
alright, mentioned this issue to @WistfulHopes (who authored this config file, and confirmed it was before i introduced all the config sanity checks), we should have this closed as soon as the new config is uploaded

**Comment by super-continent** [comment]
fixed by #27, not out on release yet but should work through downloading newest configs from master branch
