### ISSUE TITLE
Capacity overflow when parsing scr_ha BBCF script

### ISSUE THREAD

**Issue by MisterNWM** [super-continent/bbscript#29]
I'm using your BBCF Modding guide. I get this error when using: bbscript parse bbcf scr_ha.bin scr_ha.txt

Downloads\Mod>bbscript parse bbcf scr_ha.bin scr_ha.txt
thread 'main' panicked at 'capacity overflow', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-1.9.0\src\lib.rs:304:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

What should I do?

**Comment by super-continent** [comment]
interesting, seems like some sort of regression because i parsed this exact script fine before, going to look into it

**Comment by super-continent** [comment]
fixed in new commits
