### ISSUE TITLE
Rachel Alucard normal attack error

### ISSUE THREAD

**Issue by MisterNWM** [super-continent/bbscript#31]
Hello. Your program works fine, I have modified 11 different characters to suit my needs. Thank you. But I ran into a problem with Rachel Alucard. I finished editing the script file and went to check in the game. The game crashes constantly when using any normal Rachel Alucard attack. This happens at the end of the attack animation. Then I went and looked at the normal attack code. It is very different from the normal attack code of the previous characters that I edited.

Here is an example:

Izanami NmlAtk5A:

[Izanami 5A.txt](https://github.com/super-continent/bbscript/files/10950404/Izanami.5A.txt)

Rachel Alucard NmlAtk5A:

[Rachel Alucard 5A.txt](https://github.com/super-continent/bbscript/files/10950412/Rachel.Alucard.5A.txt)

I think the problem is Unknown9010, but I may be wrong.

Script files translated to txt:
Izanami:
[scr_mi.txt](https://github.com/super-continent/bbscript/files/10950423/scr_mi.txt)
Rachel A.:
[scr_rc.txt](https://github.com/super-continent/bbscript/files/10950424/scr_rc.txt)

**Comment by MisterNWM** [comment]
Yes. The problem was in Unknown9010. I deleted all the lines with this and after that everything works fine. As I understand it, Unknown9010 is responsible for the voices of Rachel's umbrella and her imp. Without these lines, the umbrella and the imp are silent during normal attacks.

**Comment by super-continent** [comment]
fixed in the latest commit, thank you for pointing this out! it should have the correct arguments now, just download the latest bbcf config
