### ISSUE TITLE
[ggst.ron][GUILTY GEAR STRIVE]   ERROR: Unknown instruction with name `setDamageCell`   

### ISSUE THREAD

**Issue by SilverDash** [super-continent/bbscript#39]
Updated ron along with other community distributed versions cause this error on build.

ERROR: Unknown instruction with name `setDamageCell`

**Comment by super-continent** [comment]
`setDamageCell` only exists in Xrd, are you rebuilding an Xrd script with the GGST config? To ensure all names are consistent across versions you should parse the bbscript files again with the current config.

**Comment by super-continent** [comment]
I would recommend downloading the latest release and using the embedded configs through the `--game <GAME>` flag from now on to ensure 1 source of truth for parsed scripts. If you re-parse the scripts it will name all instructions according to the config and will be able to rebuild them.

**Comment by SilverDash** [comment]
> I would recommend downloading the latest release and using the embedded configs through the `--game <GAME>` flag from now on to ensure 1 source of truth for parsed scripts. If you re-parse the scripts it will name all instructions according to the config and will be able to rebuild them.

I'll get around to testing this today and report back. I did end up using --Game with the latest version before posting this issue though. Assuming that doesn't use the Ron file.

If you have access to Strive I would also double check to make sure it's not just a me issue.

**Comment by super-continent** [comment]
I can test, but which script file are you trying to rebuild? Did you parse it yourself beforehand? I checked the git history of this repo and it seems that `setDamageCell` never existed in the Strive config as far as I can tell, might've missed it somewhere but it looks like the script you're using as input might have been parsed with the Xrd script
